apiVersion : apps/v1
kind: Deployment
metadata:
  name: "newcluster-dec4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "newcluster-dec4"
  template:
    metadata:
      labels:
        app: "newcluster-dec4"
    spec:
      containers:
        - name: "newcluster-dec4"
          image: "newregistry789.azurecr.io/newcluster"
          ports:
          - containerPort: 80